PUT {{host}}/data/batch/1
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "response_options": {
    "delay": 15,
    "nullCount": false
  }
}

###

PUT {{host}}/data/batch/2
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}


###