PUT {{host}}/data/options/1
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "options": {
    "format": [
      "csv"
    ]
  }
}

###

PUT {{host}}/data/options/1?filters={"ids": [3, 4, 5, 6]}&sort={"field": "id"}
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "response_options": {
    "errors": 9,
    "skipped": 0,
    "delay": 0,
    "nullCount": true,
    "response": ["static_success"]
  }
}

###

PUT {{host}}/data/options/2
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "options": {
    "format": [
      "csv2"
    ]
  }
}

###

PUT {{host}}/data/options/2
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "options": {
    "format": [
      "csv2"
    ]
  }
}

###
